// Fix: Implementing the full geminiService to resolve module and compilation errors.
import { GoogleGenAI, GenerateContentResponse, Type, Modality } from "@google/genai";

// Always use new GoogleGenAI({apiKey: process.env.API_KEY});
let aiInstance: GoogleGenAI | null = null;

const getAiClient = (): GoogleGenAI => {
  let key = '';
  if (typeof window !== 'undefined') {
    const localKey = localStorage.getItem('GOW_GEMINI_API_KEY');
    if (localKey && localKey.trim() !== '') {
      key = localKey;
    }
  }
  if (!key) {
    key = (process.env.GEMINI_API_KEY || process.env.API_KEY) as string;
  }
  if (!key || key === "PLACEHOLDER_KEY" || key.trim() === "") {
    throw new Error("MISSING_API_KEY");
  }
  if (!aiInstance) {
    aiInstance = new GoogleGenAI({
      apiKey: key,
      httpOptions: {
        headers: {
          'User-Agent': 'aistudio-build',
        }
      }
    });
  }
  return aiInstance;
};

// Helper to extract text from response and safely strip any markdown formatting
const getText = (response: GenerateContentResponse): string => {
  let text = response.text || '';
  // Strip any markdown HTML block fences if generated by the AI
  if (text.includes('```html')) {
    text = text.substring(text.indexOf('```html') + 7);
    if (text.includes('```')) {
      text = text.substring(0, text.indexOf('```'));
    }
  } else if (text.includes('```')) {
    text = text.substring(text.indexOf('```') + 3);
    if (text.includes('```')) {
      text = text.substring(0, text.indexOf('```'));
    }
  }
  return text.trim();
};

/**
 * A robust wrapper for API calls that implements a retry mechanism with exponential backoff.
 * This is crucial for handling API rate limits (quota errors) gracefully without failing immediately.
 * @param apiCall The function that makes the actual API call.
 * @returns The result of the API call.
 * @throws Throws an error if the API call fails after all retry attempts.
 */
const apiWithRetry = async <T>(apiCall: () => Promise<T>): Promise<T> => {
  let attempt = 0;
  const maxRetries = 3;
  const initialDelay = 1000; // 1 second

  while (attempt < maxRetries) {
    try {
      return await apiCall();
    } catch (error: any) {
      attempt++;
      // Check for common rate limit/quota error indicators in the error message
      const isQuotaError = error.toString().includes('429') || /quota|rate limit/i.test(error.toString());

      if (isQuotaError && attempt < maxRetries) {
        // Exponential backoff: 1s, 2s, 4s
        const delay = initialDelay * Math.pow(2, attempt - 1);
        console.warn(`Quota error detected. Retrying in ${delay}ms... (Attempt ${attempt}/${maxRetries})`);
        await new Promise(resolve => setTimeout(resolve, delay));
      } else {
        console.error("API call failed after multiple retries or for a non-quota reason.", error);
        // After final retry, or for non-quota errors, throw it to be handled by the UI
        throw error;
      }
    }
  }
  // This should theoretically not be reached, but it's a safeguard.
  throw new Error("API call failed after maximum retries.");
};


// 1. generateAppCode
export const generateAppCode = async (prompt: string, appMode: string): Promise<string> => {
  const model = 'gemini-3.5-flash'; // For complex coding tasks
  
  const systemInstruction = `You are an elite, legendary Awwwards-winning experiential web designer and front-end developer, globally renowned for building breathtaking, premium, interactive landing pages that represent the absolute pinnacle of digital craft and UI design.
Your response MUST be ONLY the complete, fully formed HTML code. Do NOT include any markdown code block wrappers (like \`\`\`html) or raw text commentary. Just start with \`<!DOCTYPE html>\` and end with \`</html>\`.

--- THE AWWWARDS-GRADE VISUAL, ANIMATION, & STOCK IMAGE MANDATE ---

1. MANDATORY IMPORTS & FRAMEWORKS (Ensure these CDNs are imported correctly to avoid rendering errors):
   - Tailwind CSS: \`<script src="https://cdn.tailwindcss.com"></script>\`
   - GSAP (GreenSock) for elite professional motion paths: \`<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.2/gsap.min.js"></script>\`
   - GSAP ScrollTrigger for scrollytelling timelines: \`<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.2/ScrollTrigger.min.js"></script>\`
   - Lucide Icons (CDN): \`<script src="https://unpkg.com/lucide@latest"></script>\`
   - Premium Typography (Google Fonts): 
     \`<link href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300;400;550;700&family=Syne:wght@700;800&family=Plus+Jakarta+Sans:wght@300;400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet">\`
   - Initialize Lucide Icons at the end of your script with: \`lucide.createIcons();\`

2. HIGH-POLISH UI DESIGN & SPATIAL LUXURY:
   - Configure Tailwind so default fonts map perfectly:
     \`<script>
       tailwind.config = {
         theme: {
           extend: {
             fontFamily: {
               sans: ['"Plus Jakarta Sans"', 'sans-serif'],
               heading: ['"Syne"', 'sans-serif'],
               mono: ['"JetBrains Mono"', 'monospace'],
               display: ['"Space Grotesk"', 'sans-serif'],
             }
           }
         }
       }
     </script>\`
   - Space and Density: Embrace asymmetric layouts, clean modern grid structures, and generous negative space. Do not cram components.
   - Elegant Backdrops: Implement premium blurry glass overlays (\`backdrop-filter: blur(20px)\`), fine satin borders (\`border border-white/5\`), and soft glowing mesh spheres floating in the background to establish deep visual atmosphere.

3. DIRECTIVES FOR BEAUTIFUL STOCK IMAGES FROM PEXELS & UNSPLASH:
   - YOU MUST NOT use low-quality placeholder boxes, SVGs, solid gray squares, or pattern grids for primary visual elements.
   - Use actual high-resolution, stunning, public stock photography URLs from Unsplash (\`https://images.unsplash.com/\`) or Pexels (\`https://images.pexels.com/\`).
   - Use realistic image URLs that actually load high-quality visuals fitting the topic, with proper width limiters for fast performance (e.g. \`?auto=format&fit=crop&q=80&w=1200\`).
   - EXAMPLES OF GORGEOUS, TESTED VISUAL STOCK TARGETS:
     * Minimalist High-End Workspace/Desk: \`https://images.unsplash.com/photo-1499951360447-b19be8fe80f5?auto=format&fit=crop&q=80&w=1200\`
     * Cosmic Space Nebula/Satellite: \`https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80&w=1200\`
     * Futuristic Neon Cybercityscape: \`https://images.unsplash.com/photo-1508739773434-c26b3d09e071?auto=format&fit=crop&q=80&w=1200\`
     * Atmospheric Geometric Abstract Render: \`https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&q=80&w=1200\`
     * Luxury White Minimalist Product Shot: \`https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&q=80&w=1200\`
     * Premium Cattle in Organic Alpine Sun (for GOW mode): \`https://images.unsplash.com/photo-1570042225831-d98fa7577f1e?auto=format&fit=crop&q=80&w=1200\`
   - Align the photography strictly with the requested website subject to make the interface look exceptionally cinematic and organic!

4. AWWWARDS-LEVEL MOTION & INTERACTION RULES:
   - REDUCE CLUTTERED TEXT ANIMATIONS: Do NOT use character-by-character letter-splitting on normal paragraphs, long texts, grids, or body copy. It is unreadable and chaotic. Preserve text split transitions ONLY for the single, main hero display heading!
     \`// Example Splitting Utility strictly for main hero title:
     const splitHeading = (el) => {
       el.innerHTML = el.textContent.split('').map(c => \\\`<span class="char-span inline-block select-none" style="transition: transform 0.4s cubic-bezier(0.175, 0.885, 0.32, 1.275);">\${c === ' ' ? '&nbsp;' : c}</span>\\\`).join('');
     };\`
   - MAGNETIC INTERACTION: Build real physical magnetic pull forces on buttons and high-importance links:
     \`document.querySelectorAll('.magnetic-target').forEach(btn => {
       btn.addEventListener('mousemove', (e) => {
         const rect = btn.getBoundingClientRect();
         const x = e.clientX - rect.left - rect.width / 2;
         const y = e.clientY - rect.top - rect.height / 2;
         gsap.to(btn, { x: x * 0.35, y: y * 0.35, duration: 0.3, ease: "power2.out" });
       });
       btn.addEventListener('mouseleave', () => {
         gsap.to(btn, { x: 0, y: 0, duration: 0.6, ease: "elastic.out(1, 0.3)" });
       });
     });\`
   - GLASS HOVER INTEGRITY & 3D TILT EFFECT: Fully implement a clean mouse tilt on grid cards so they rotate in 3d space on mouse hover:
     \`document.querySelectorAll('.tilt-card').forEach(card => {
       card.addEventListener('mousemove', (e) => {
         const rect = card.getBoundingClientRect();
         const xAxis = (rect.width / 2 - (e.clientX - rect.left)) / 12;
         const yAxis = ((e.clientY - rect.top) - rect.height / 2) / 12;
         card.style.transform = \\\`perspective(1000px) rotateY(\${xAxis}deg) rotateX(\${yAxis}deg) scale3d(1.02, 1.02, 1.02)\\\`;
       });
       card.style.transition = 'transform 0.15s ease-out';
       card.addEventListener('mouseleave', () => {
         card.style.transform = 'perspective(1000px) rotateY(0deg) rotateX(0deg) scale3d(1, 1, 1)';
       });
     });\`
   - HERO IMAGE MASKS: Include ScrollTrigger logic that scales and reveals hero imagery outwards using clip-paths or expanding containers as the reader scrolls down.

5. EXTRAORDINARY MOBILE COMPATIBILITY:
   - Ensure all layouts are beautifully responsive. Containers must be configured with fluid sizes (\`w-full max-w-7xl mx-auto\`) and responsive grid columns (\`grid-cols-1 md:grid-cols-3\`).
   - Use fluid typography (\`text-[7vw] md:text-[4vw]\`) for titles to look grand on desktop but perfectly scaled on mobile monitors.

6. ELEGANT FLOATING CURSOR & LIQUID MOVEMENT:
   - Add a custom floating magnetic cursor or liquid tracker in the webpage. Drive the coordinates smoothly in vanilla JS using a linear interpolation (lerp) or a high-performance GSAP requestAnimationFrame ticker. Make the cursor grow, invert, or display text tags when hovering over cards, interactive items, or buttons.

7. STRUCTED SCENOGRAPHY & REAL HINDI IN GOW MODE:
   - Plan 4-5 core thematic blocks: Hero stage, Philosophical Core, Experiential Interactive Spec Grid, dynamic client-side accordion details, and a high-feedback CTA block.
   - For GOW mode settings: All user-visible text MUST be in highly witty, absolutely hilarious, and professional Hindi, fully reflecting bovine humor, organic milk streams, and rural wisdom, layered over the most expensive, gorgeous Awwwards-worthy tech interface!

Create a monumental masterpiece of web design that works perfectly, feels incredibly fluid, and looks absolutely stunning.`;

  const response = await apiWithRetry(() => getAiClient().models.generateContent({
    model,
    contents: prompt,
    config: {
      systemInstruction,
    },
  }));

  return getText(response);
};

// 2. enhancePrompt
export const enhancePrompt = async (prompt: string, appMode: string): Promise<string> => {
  const model = 'gemini-3.1-flash-lite'; // Ultra-fast, highly responsive model
  const systemInstruction = `You are an expert AI prompt engineer specializing in award-winning web design. Your task is to take a user's simple idea and rewrite it into a single, highly detailed prompt that instructs an AI to build an experiential, Awwwards-level website.
The new prompt must transform the user's idea into a NARRATIVE JOURNEY. It must explicitly request **a clear story, cinematic scrollytelling, a central interactive 3D scene, bold animated typography, and polished micro-interactions.**

The user is in "${appMode}" mode.
- If in "GOW" mode, the prompt must request a technically flawless, Awwwards-level website for a hilarious and absurd story. The prompt must also specify that all content should be in simple, witty Hindi. (e.g., "Create a cinematic scrollytelling website telling the story of a philosophical potato's quest for enlightenment. Feature a central, rotating 3D potato model and bold Hindi typography.")
- If in "NORMAL" mode, the prompt must be professional and sophisticated, describing a cutting-edge, visually stunning website for a legitimate purpose. (e.g., "Design an immersive, narrative-driven journey through the history of space exploration, featuring interactive 3D models of rockets that animate as you scroll.")

Respond with ONLY the enhanced prompt text. Do not include any other text. Keep it concise, brief, and highly directed (under 120 words).`;

  const response = await apiWithRetry(() => getAiClient().models.generateContent({
    model,
    contents: `Here is the user's idea: "${prompt}"`,
    config: {
      systemInstruction,
      temperature: 0.3,
      maxOutputTokens: 180,
    },
  }));

  return getText(response);
};


// 3. modifyAppCode
export const modifyAppCode = async (generatedCode: string, modificationPrompt: string, appMode: string, modificationType: 'website' | 'chatbot'): Promise<string> => {
    const model = 'gemini-3.5-flash'; // For complex coding tasks
    
    const systemInstruction = `You are an elite, legendary Awwwards-winning front-end engineer modifying an existing world-class, experiential HTML landing page.
Your response MUST be ONLY the complete, fully formed modified HTML code. Do NOT include any markdown code block wrappers (like \`\`\`html) or raw text commentary. Just start with \`<!DOCTYPE html>\` and end with \`</html>\`.

--- REVISION MANDATES ---
- **Enrich Experiential Elements**: Ensure changes preserve and amplify Awwwards-worthy design assets, including GSAP scrolling, CSS 3D tilt effects, magnetic interactions, and custom fluid cursors.
- **Maintain Beautiful Stock Images**: Keep or inject high-resolution, stunning public stock photos from Unsplash (https://images.unsplash.com/) or Pexels (https://images.pexels.com/) instead of grey placeholder blocks or low-quality svgs. Use proper width limits such as ?auto=format&fit=crop&q=80&w=1200.
- **Tame Chaotic Text Splits**: Avoid splitting long paragraphs and body-text into individual characters. Restrict character-by-character letter animations strictly to the main hero primary heading to keep the interface legible and extremely professional.
- **Maintain Robust Scripts**: Do not break existing mouse interaction scripts (magnetic links, custom cursor trails, Lucide Icon setups, or GSAP timelines). Incorporate edits natively into the layout.
- **Always Include CSS & JS**: Never return truncated segments or single components. Always output the entire HTML document.
- **Hindi Localization**: In Gow Mode, ensure all user-visible text is hilarious, witty Hindi, styled with the most expensive tech interface aesthetics.`;
    
    const userPrompt = `Modification request from the user: "${modificationPrompt}"
    
Here is the original HTML code to modify (make sure to return the FULL modified document without truncation):
${generatedCode}
`;

    const response = await apiWithRetry(() => getAiClient().models.generateContent({
        model,
        contents: userPrompt,
        config: {
            systemInstruction
        }
    }));

    return getText(response);
};

// 4. generateImage
export const generateImage = async (prompt: string): Promise<string> => {
    const model = 'gemini-2.5-flash-image'; // For general, fast image generation
    
    const response: GenerateContentResponse = await apiWithRetry(() => getAiClient().models.generateContent({
        model,
        contents: {
            parts: [{ text: prompt }],
        },
        config: {
            responseModalities: [Modality.IMAGE],
        },
    }));
    
    for (const candidate of response.candidates ?? []) {
        for (const part of candidate.content.parts) {
            if (part.inlineData) {
                const base64ImageBytes: string = part.inlineData.data;
                const mimeType = part.inlineData.mimeType;
                return `data:${mimeType};base64,${base64ImageBytes}`;
            }
        }
    }

    throw new Error('Image generation failed: no image data received from the model.');
};


